services:
  database:
    image: postgres:15
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    networks:
      - backend

  nginx_web:
    image: nginx:stable-alpine
    container_name: nginx_web
    ports:
      - "80:80"
    volumes:
      - ./GameSpotlight/docker/nginx/conf.d:/etc/nginx/conf.d:rw
    depends_on:
      - symfony_app
    networks:
      - backend

  symfony_app:
    container_name: symfony_app
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - database
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: "postgresql://myuser:mypassword@database:5432/mydatabase"
    networks:
      - backend

networks:
  backend:
