services:
  database:
    image: mysql:8
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: symfony
      MYSQL_PASSWORD: symfony
    ports:
      - "3307:3306"
    networks:
      - backend

  nginx_web:
    image: nginx:stable-alpine
    container_name: nginx_web
    ports:
      - "80:80"
    volumes:
      - ./docker/nginx/conf.d:/etc/nginx/conf.d:rw
    depends_on:
      - symfony_app
    networks:
      - backend

  symfony_app:
    container_name: symfony_app
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - database
    expose:
      - 9000
    networks:
      - backend

networks:
  backend:
